services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    environment:
      - TZ=${TimeZone}
    env_file:
      - .env.nginx
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  dnsmasq:
    build: ./dnsmasq
    container_name: dnsmasq
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - ./dnsmasq/dnsmasq.d:/etc/dnsmasq.d:ro
    environment:
      - TZ=${TimeZone}
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "4"

  web:
    build: ./web
    container_name: web
    restart: always
    volumes:
      - ./dnsmasq/dnsmasq.d:/app/dnsmasq/dnsmasq.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TimeZone}
    env_file:
      - .env.web
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "4"
